swagger: '2.0'
basePath: /secrets/v1
info:
  version: 1.0.0
  title: ' DC/OS Secrets API'
tags:
  - name: backend
    description: Secret stores related API endpoints
  - name: secrets
    description: Secrets manipulation
securityDefinitions:
  token:
    type: apiKey
    in: header
    name: Authorization
security:
  - token: []
paths:
  /secret/{store}/{path-to-secret}:
    get:
      tags:
        - secrets
      operationId: get-secret
      summary: Read or list a secret from the store by its path.
      description: Read or list a secret from the store by its path.
      parameters:
        - name: store
          description: The backend store from which to get the secret.
          in: path
          required: true
          type: string
        - name: list
          in: query
          description: |
            If set to true, list only secret keys.
          type: string
        - name: path-to-secret
          description: The path to store the secret in.
          in: path
          required: true
          type: string
      responses:
        200:
          description: Response body contains secret authorized content.
          schema:
            $ref: '#/definitions/Secret'
        400:
          description: Unsupported Accept header.
        403:
          description: Forbidden.
        404:
          description: Secret not found.
    put:
      tags:
        - secrets
      operationId: create-secret
      summary: Create a secret in the store at the path.
      description: Create a secret in the store at the path.
      parameters:
        - in: body
          name: body
          description: Secret value.
          required: true
          schema:
            $ref: '#/definitions/Secret'
        - name: store
          description: The backend to store the secret in.
          in: path
          required: true
          type: string
        - name: path-to-secret
          description: The path to store the secret in.
          in: path
          required: true
          type: string
      responses:
        201:
          description: Secret created.
        400:
          description: Unsupported Content-Type header.
        403:
          description: Forbidden.
        409:
          description: Secret already exists.
    patch:
      tags:
        - secrets
      operationId: update-secret
      summary: Update secret.
      description: Update existing secret in the specified store.
      parameters:
        - in: body
          name: body
          description: Secret value.
          required: true
          schema:
            $ref: '#/definitions/Secret'
        - name: store
          description: The backend to store the secret in.
          in: path
          required: true
          type: string
        - name: path-to-secret
          description: The path for the secret to update.
          in: path
          required: true
          type: string
      responses:
        204:
          description: Secret updated.
        403:
          description: Forbidden.
        404:
          description: Secret not found.
    delete:
      tags:
        - secrets
      operationId: delete-secret
      summary: Delete a secret.
      description: Delete a secret.
      parameters:
        - name: store
          description: The backend to delete the secret from.
          in: path
          required: true
          type: string
        - name: path-to-secret
          description: The path to the secret to delete.
          in: path
          required: true
          type: string
      responses:
        204:
          description: Success.
        403:
          description: Forbidden.
        404:
          description: Secret not found.
definitions:
    Secret:
      type: object
      properties:
        value:
          type: string
      additionalProperties: false
